server:
  port: 6869 #服务端口

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://itcast:itcast123@127.0.0.1:6868/eureka/
    instance:
      prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
  server:
    enable-self-preservation: false #禁用自我保护模式(true为启用,false为禁用)
security:
  basic:
    enable: true #开启基于HTTP basic的认证
  user: #配置用户的账号信息
    name: itcast
    password: itcast123
